FROM ubuntu:bionic
MAINTAINER Daniel Boline

RUN apt-get update && \
    apt-get install -y curl pkg-config checkinstall gcc libssl-dev ca-certificates \
            file build-essential autoconf automake autotools-dev libtool xutils-dev \
            git libusb-dev libxml2-dev libpq-dev && \
    rm -rf /var/lib/apt/lists/* && \
    curl https://sh.rustup.rs > rustup.sh && \
    sh rustup.sh -y && \
    . ~/.cargo/env

WORKDIR /movie_collection_rust

ADD Cargo.toml /movie_collection_rust
ADD src /movie_collection_rust/src
ADD scripts /movie_collection_rust/scripts
ADD Makefile /movie_collection_rust
ADD templates /movie_collection_rust/templates
# ADD python /movie_collection_rust/python
