[package]
name = "transcode_lib"
version = "0.6.24"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
movie_collection_lib = {path = "../movie_collection_lib"}
anyhow = "1.0"
deadpool = "0.5"
deadpool-lapin = "0.6"
lapin = "1.5"
derive_more = "0.99"
futures = "0.3"
log = "0.4"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"

[dev-dependencies]
tokio = {version="0.2", features=["full"]}
stdout-channel = { git = "https://github.com/ddboline/stdout-channel-rs.git", branch="tokio_02" }
