name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.4-alpine
        env:
          POSTGRES_DB: movie_queue
          POSTGRES_PASSWORD: 2UtcMAAvNuBHPqK9
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install libpq-dev && rustup update

    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic

    - name: Build
      run: |
        cargo build --workspace

    - name: Run tests
      run: |
        psql $DATABASE_URL < ./scripts/authorized_users.sql && \
        psql $DATABASE_URL < ./scripts/imdb_ratings.sql && \
        psql $DATABASE_URL < ./scripts/imdb_episodes.sql && \
        psql $DATABASE_URL < ./scripts/movie_collection_on_dvd.sql && \
        psql $DATABASE_URL < ./scripts/movie_collection.sql && \
        psql $DATABASE_URL < ./scripts/movie_queue.sql && \
        psql $DATABASE_URL < ./scripts/trakt_watched_episodes.sql && \
        psql $DATABASE_URL < ./scripts/trakt_watched_movies.sql && \
        psql $DATABASE_URL < ./scripts/trakt_watchlist.sql && \
        cargo test --verbose --workspace && \
        cargo install cargo-tarpaulin && \
        cargo tarpaulin --verbose --all-features --workspace --out Xml
      env:
        DATABASE_URL: postgresql://postgres:2UtcMAAvNuBHPqK9@localhost:5432/movie_queue

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
